### Playbook default settings
node: "awx"
compose_dir: "/opt"
awx_compose_dir: "{{ compose_dir }}/awx"
isolated_compose_dir: "{{ compose_dir }}/awx-isolated"
postgres_compose_dir: "{{ compose_dir }}/postgres"
webhook_compose_dir: "{{ compose_dir}}/webhook"
external_database: "no"
enable_webhooks: "no"
github_secret: "webhook_secret"
python_executable: /usr/bin/python

### Docker default settings
docker_registry: "dockerhost"
awx_version: "17.0.1"
docker_registry_namespace: "ansible"
awx_image: "awx"
awx_isolated_image: "awx_isolated"
awx_docker_actual_image: "{{ docker_registry_namespace }}/{{ awx_image }}:{{ awx_version }}"
awx_isolated_docker_actual_image: "{{ docker_registry }}/{{ docker_registry_namespace }}/{{ awx_isolated_image }}:{{ awx_version }}"
awx_webhook_docker_actual_image: "{{ docker_registry }}/{{ docker_registry_namespace }}-webhook:{{ webhook_version }}"
docker_network_name: "awx"
docker_network_host_mode: false

### AWX Default Settings
admin_user: "admin"
admin_password: "password"
awx_secret_key: "awxsecret"
automation_user: "{{ admin_user }}"
automation_password: "{{ admin_password }}"
broadcast_websocket_secret: "nJaRixlmocgQSzjW5pWr"
awx_host: "set_awx_fqdn"

ssl_certificate: |
  
ssl_key: |
  

awx_isolated_nodes: false
awx_isolated_ssh_keys_external: false
awx_isolated_ssh_keys_private:
  key1: |
    
#  When awx_isolated_ssh_keys_external: false - put 'docker exec -ti awx_task awx-manage generate_isolated_key' output here. And comment out awx_isolated_ssh_keys_private variable.
awx_isolated_ssh_keys_public: |
  ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCaM9GL+vN5/B9EyEVqUkVhMahCYNjSp9JCK9qJSq4WxWRSmaI48ONWmtJhuEaScXQ8rkZF/ZfDoMt61pLM7hpAWIcQf3f8z5AKRhnP7b9GQ++cj3hKlFPvtMfdpWi5oFIcwdyPlCO2JpN73LSAe00umdJ+LurHucUqvxFRL4h8AJf2WXJzonRqQBHud+5i6PLy3aKTQP2MHgwu8V8rms7x5iNdh7V6tvBAujhrhILnVaxPZnXYoQ0bFjTrwJFFY6otjGhgyhX+WCvLCNopUT6NKeEAStSp6guySetlDM0JEoSlUq2kti9HIgBI8SyEH1romN8oeInVwdFEhGT3hv3PSKESePjds8AyoFZVdD01yw6uUIk0TseSq5drlt+/XqpsRgwUdMJLMQ69QsLXReZJqc8DZm4qJwccvdHhkJvYn+ANrUYWlKyQe5TfblyyIIBlWsviyJ7wXu+6+V93sviXCUPUixMbqg0NGWS6Ws+kNVBCQT3xOd5byh4gg+mXigj4iS8FwmwduqkDasa2WP5mmM+qhqP4cPqzPzCxX6T0DSB8QqeSEg13oKCswl7+dh8TLJahHGvKW2EHJvajf3t4QIJdEr5y/atXZ6GM7iXHcTZFcO2XjkXRynaBgV+1DvQ7qcTekDTTAYOCqEswavvEi4NgXPVTPBuVC+k3/wituQ== pub@key1

awx_isolated_ssh_config:
  awxn001iso.domain:
    HostName: 10.13.55.161
    Port: 2022
    IdentityFile: /root/.ssh/key1

### Postgres DB details
pg_version: "12"
pg_hostname: "set_database_hostname"
pg_password: "awxpass"
pg_port: "5432"
pg_username: "awx"
pg_database: "awx"

### Redis details
redis_version: "6"

### Webhook default settings
webhook_version: "2.6.9-1"

# https://awx.hostname:9000/hooks/awx-project-{{ name }}
webhook_awx_projects:
  - id: 11
    name: sample-handbook
    secret: "{{ github_secret }}"
  - id: 13
    name: magic-repo
    secret: "{{ github_secret }}"
  - id: 41
    name: test-project
    secret: "{{ github_secret }}"
  - id: 56
    name: test-product
    secret: "{{ github_secret }}"

# https://awx.hostname:9000/hooks/awx-job-{{ name }}
webhook_awx_jobs:
  - id: 700
    name: test-job
    branch: test_branch
    secret: test-secret-word
  - id: 34
    name: test-job2
    branch: master
    secret: "{{ github_secret }}"
